Hi there, you seem to want to comment on this post:

{{user_id}}-AT-{{domain}}-{{post_name}}@{{host}}

Since we don't know who you are, we can't just let you go 
commenting without some kind of verification.  Someone could
trying to comment in your name or sign you up for something
you don't want.

With that in mind, simply hit reply to this message or send an email to:

{{ confirm_address }}@{{host}}

Once you send that then we'll make your page using your original
message.

** Don't worry, your original comment is not lost. **

We'll make it all happen right when you confirm your request.

Thanks!

---
OneShotBlog(TM)
http://{{host}}/
A Lamson project example http://lamsonproject.org/
