Received: from bazar2.conectiva.com.br (bazar2.conectiva.com.br [127.0.0.1])
	by bazar2.conectiva.com.br (Postfix) with ESMTP id D906B18AD6;
	Sun, 21 Jun 2009 17:42:54 -0300 (BRT)
X-Original-To: lua@bazar2.conectiva.com.br
Delivered-To: lua@bazar2.conectiva.com.br
Received: from smtp-out-01.simnet.is (smtp-out-01.simnet.is [194.105.231.27])
	by bazar2.conectiva.com.br (Postfix) with ESMTP id E2C9118A1B
	for <lua@bazar2.conectiva.com.br>; Sun, 21 Jun 2009 17:42:50 -0300 (BRT)
Authentication-Results: smtp-out-01.simnetpro.is;
	dkim=neutral (message not signed) header.i=none
X-SBRS: 0.8
X-IronPort-Anti-Spam-Filtered: true
X-IronPort-Anti-Spam-Result: Au4KAKo4PkrCaedFbGdsb2JhbACYXwsOCQcTswaECgU
X-IronPort-AV: E=Sophos;i="4.42,264,1243814400"; d="scan'208";a="222914853"
Received: from consumer-mta-01.simnet.is ([194.105.231.69])
	by smtp-out-01.simnetpro.is with ESMTP; 21 Jun 2009 20:42:38 +0000
Subject: Re: Problem Integrating Lua with Visual Studio 2005
From: =?ISO-8859-1?Q?Gabr=EDel?= "A." =?ISO-8859-1?Q?P=E9tursson?=
	<gabrielp@simnet.is>
To: Lua list <lua@bazar2.conectiva.com.br>
In-Reply-To: <dbaa5cbe0906211336uf58d390r94f5da3017d0fd5c@mail.gmail.com>
References: <dbaa5cbe0906211336uf58d390r94f5da3017d0fd5c@mail.gmail.com>
Content-Type: text/plain
Date: Sun, 21 Jun 2009 20:42:38 +0000
Message-Id: <1245616958.16548.2.camel@debian.lan>
Mime-Version: 1.0
X-Mailer: Evolution 2.26.1.1 
Content-Transfer-Encoding: 7bit
X-BeenThere: lua@bazar2.conectiva.com.br
X-Mailman-Version: 2.1.6
Precedence: list
Reply-To: Lua list <lua@bazar2.conectiva.com.br>
List-Id: Lua list <lua.bazar2.conectiva.com.br>
List-Unsubscribe: <http://bazar2.conectiva.com.br/mailman/listinfo/lua>,
	<mailto:lua-request@bazar2.conectiva.com.br?subject=unsubscribe>
List-Archive: <http://bazar2.conectiva.com.br/mailman/private/lua>
List-Post: <mailto:lua@bazar2.conectiva.com.br>
List-Help: <mailto:lua-request@bazar2.conectiva.com.br?subject=help>
List-Subscribe: <http://bazar2.conectiva.com.br/mailman/listinfo/lua>,
	<mailto:lua-request@bazar2.conectiva.com.br?subject=subscribe>
Sender: lua-bounces@bazar2.conectiva.com.br
Errors-To: lua-bounces@bazar2.conectiva.com.br
X-Spambayes-Classification: ham; 0.00

You may start by telling us what kind or errors you are experiencing.

On Sun, 2009-06-21 at 16:36 -0400, shanthan raj wrote:
> Hi,
> 
> I'm new to Lua. I want to develop a game using Lua. I'm planning to
> use Visual Studio 2005 for the development. I have downloaded [VS Lua
> Language Pack] (5.1) . When a run a simple program in Lua using Visual
> Studio, I'm getting some errors. May be I'm doing something wrong. Can
> anybody guide how to start with a simple "Hello World" program.
> 
> Thanks in Advance,
> 
> Raj
