Hi,

This is a receive-only service for filtering email from non-registered
users.  That means we can't let you email another user from your
account, and in fact if you keep trying to do it we'll change you to a
marketroid classification instead.

If we let you do this, then marketroids could just subscribe for the
service themselves and then continue spamming people through their own
MyInboxIsNotA.TV account.


YOUR MESSAGE IS DROPPED

The email you just sent is dropped.  If we see many of these attempts
from your account we'll reclassify you as a marketroid and publish your
address on the wall of shame.

Don't worry, we'll warn you before we do this, but consider this the
first step.


TESTING YOUR SHIELD ADDRESS

If you are trying to test your address, then go use another email
address from a free webmail service.


Thanks,

MyInboxIsNotA.TV

