Hi,

So you're interested in MyInboxIsNotA.TV are you?  Well, before we can
let you use our service we have to get you to confirm that you really
want to use it.  If we don't then someone could subscribe you without
your consent.


CONFIRMING

To confirm that you want to start using our server, simply reply to this
message.  Put anything you want in the body and subject.  When we
receive your reply we'll sign you up and send you instructions on using
MyInboxIsNotA.TV.


LEGAL STUFF

By replying to this email you agree that we can terminate your service
at any time, that we do not guarantee security or confidentiality, and
that we will give your email address and history to any law enforcement
agency that asks politely.  Replying means you understand that we will
gleefully rat your ass out if you're doing anything moderately illegal.

However, we do promise to *never* give your real address to any marketroid
unless they sue us to find out who you are.


Thanks,

MyInboxIsNotA.TV
