Welcome,

You are now allowed to use MyInboxIsNotA.TV to communicate with annoying
people who might send you spam, HTML email, or who you just don't want
to give your real address to.

The goal of our service is to make it clear that people who try to
market to you should not assume that sending you an email is like making
you watch a TV commercial.  If they don't get this, then they shouldn't
be using email for customer development.


YOUR SHIELD ADDRESS

When you want to signup for a service, simply give out this address:

{{ user_anon }}

Remember it!  Write it down!  This is important!


HOW IT WORKS

When you give your SHIELD ADDRESS (you wrote it down right?) to a
service, you are not giving your real address to them.  Now when they
try to send you an email, it comes to myinboxisnota.tv first.

We then rewrite it so that it gets sent to you, and give you a special
"marketroid" address to talk with them over.  You get to see the
original sender, but replying to this email will go back to
myinboxisnota.tv.

When we receive a reply to this marketroid address, we rewrite it so
that any semblance of your identity is removed from the headers and
replaced with {{ user_anon }}.


CAUTIONS

If you want to remain anonymous, you should probably make sure you do
the following:

* Remove anything identifying you from your signature.
* Try not to use your real name with the service.
* Don't use your real name in any correspondence.


Thanks,

MyInboxIsNotA.TV

