Hi,

You (or someone pretending to be you) has asked to {{action}}
{{list_name}}, but before I can do that I need you to confirm that you
really want to do this.  I know, I know, you hate having to confirm
everything you do, but if I don't confirm your request, then someone who
hates you can forge your identity.

We wouldn't want that now would we?  Good!


CONFIRM BY REPLYING

If you really did mean {{ list_name }}, then reply to this message
and I'll do it right away.  I'll send you one more message telling you
when I'm done.

Thank You,

      librelist.com

