Hi,

You are now subscribed to the {{list_name}} mailing list, and your
original email has NOT been forwarded to the mailing list.


YOUR FIRST MAIL WAS DROPPED

Sorry about that, but you'll have to resend that email now that
you're subscribed.


UNSUBSCRIBING

Now that you're subscribed to {{list_name}} you probably want to
remember a few email addresses you can use to manage your subscription:

* {{list_name}}-unsubscribe@{{host}}
  - Send to this address to unsubscribe from the list.

That's all there is to it.  Enjoy, and be nice please.


Thank You,

      librelist.com
