Hi,

You are successfully unsubscribed from {{list_name}} and won't receive
any more emails from them.  This means that, if this list archives were
closed, then you won't have access anymore.  


GETTING BACK ON

If you want to subscribe again then just send an email to:

{{list_name}}-subscribe@{{host}}

You'll have to confirm again, but that is all.

Well, we're sad to see you go, and hope you enjoyed using the service.

Thank You,

      librelist.com
