Hi,

We tried contacting you about this, but your email account bounced
recently.  That was a while ago so we can't say why or how it happened,
but it did, and we had to turn off your subscriptions temporarily until
you dealt with it.

GETTING UNBOUNCED

Now that you've sent an email to {{ address }}@{{ host }} we're assuming
everything is aright, so here's what you need to do if you want to turn
everything back on:

Reply to this email and then we'll confirm that your account is working
and you'll be turned back on.

Sorry about this, but it had to be done so everyone else could enjoy
librelist.com without getting your bounce messages.

Thank You,

      librelist.com
