Hi,

It looks like your email account is bouncing, so you may not even get
this.  Your email server gave me some reasons, which I've attached
to this messages, as well as reporting this diagnostic code:

{{ reason }}

Hopefully that all means something to you and you can fix it.


ACCOUNT DISABLED

We're going to have to disable your account on all mailing lists until
you fix this problem and can receive mail.  When you fix it, try to fix
the problem permanently so that you don't continue to get disabled.


GETTING UNBOUNCED

To enable your subscriptions again, simply reply to this email and we'll
turn everything back on.  You *will* miss previously sent messages and
none of your messages you sent will be delivered until you reinstate
yourself.


GONE IN 30 DAYS

If your account stays disabled for more than 30 days then it will be
deleted.  Sorry about that, but we have to keep things sane or it will
impact the other people who use librelist.com.

Thanks You,

       librelist.com

