Hi,

Alright, looks like your account is working now.
You managed to reply to an unbounce confirmation message
so that means you can at least receive and send again.


RESEND YOUR ORIGINAL EMAIL

We had to drop your original email in order to handle
checking that your email worked, so please resend it.


AVOIDING BOUNCES IN THE FUTURE

Please make sure that whatever caused the bounce doesn't
happen again.  Here's some thing you'll want to disable
since they actually are very bad ideas you don't need
anymore:

1) Auto-away messages.  These always mess with mailing lists and are 
considered very rude, even if they work right.

2) Spam filters that send back spam results as bounces.
If your spam product works this way, please get a new spam
product.  It is both a violation of various RFCs and it is
a security hole since you are releasing information that
spammers can use to get around your filters.

3) Overly aggressive graylist systems may also return error 
messages that would cause you to bounce.  Please put your
subscriptions into your whitelist.

Thanks for your patience,

       librelist.com
